package(default_visibility = ["//visibility:public"])

licenses(["notice"])

py_library(
    name = "core",
    deps = [
        "//tensorflow_text/core/pybinds:_pywrap_fast_bert_normalizer_model_builder",
        "//tensorflow_text/core/pybinds:_pywrap_fast_wordpiece_tokenizer_model_builder",
        "//tensorflow_text/core/pybinds:_pywrap_model_converter",
        "//tensorflow_text/core/pybinds:_pywrap_phrase_tokenizer_model_builder",
        "//tensorflow_text/core/pybinds:_pywrap_whitespace_tokenizer_config_builder",
        "//tensorflow_text/core/pybinds:_tflite_registrar",
    ],
)